version: 2

project_name: ape

before:
  hooks:
    - go mod tidy
    - sh -c "cd frontend && npm ci && npm run build"

builds:
  - main: ./main.go
    binary: ape
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: Dongckim
    name: A.P.E
